app = "svelte-ai-builder"
primary_region = "iad"

[build]
  # Uses Dockerfile by default

[env]
  HOST = "0.0.0.0"
  PORT = "3000"
  NODE_ENV = "production"
  # Add ORIGIN for SvelteKit CSRF protection
  ORIGIN = "https://svelte-ai-builder.fly.dev"
  # Public URL for the app
  PUBLIC_BASE_URL = "https://svelte-ai-builder.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/healthcheck"
  protocol = "http"
  timeout = "10s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
