app = "svelte-ai-builder"
primary_region = "iad"

[build]
  # Uses Dockerfile by default

[env]
  HOST = "0.0.0.0"
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true

[[vm]]
  size = "shared-cpu-1x"
