// Layout constants
export const LAYOUT = {
	CHAT_SIZE_DEFAULT: 25,
	CHAT_SIZE_MIN: 15,
	CHAT_SIZE_MAX: 50,

	PREVIEW_SIZE_DEFAULT: 65,
	CODE_SIZE_DEFAULT: 35,

	PANE_MIN_SIZE: 20,
	CONTENT_MIN_SIZE: 40
} as const;
