<script lang="ts">
	import type { ChatMessage } from '$lib/core/stores/chat';
	import { getCodePreview, formatProvider, formatTime } from '$lib/shared/utils/codePreview';
	import {
		Copy as CopyIcon,
		Code as CodeIcon,
		Wand2 as Wand2Icon,
		Eye as EyeIcon,
		EyeOff as EyeOffIcon
	} from '@lucide/svelte';
	import { safeSessionStorage } from '$lib/shared/utils/storage';
	import { t } from '$lib/shared/i18n';
	import { createEventDispatcher } from 'svelte';

	interface Props {
		message: ChatMessage;
		onUseCode?: (code: string) => void;
		onRefine?: (messageId: string) => void;
	}

	let { message, onUseCode, onRefine }: Props = $props();
	let expanded = $state(false);
	const dispatch = createEventDispatcher<{ retry: { messageId: string } }>();

	function handleCopy() {
		if (message.generatedCode) {
			navigator.clipboard.writeText(message.generatedCode);
		}
	}

	function handleUseCode() {
		if (message.generatedCode) {
			onUseCode?.(message.generatedCode);
		}
	}

	function handleRefine() {
		onRefine?.(message.id);
	}

	$effect(() => {
		// Load saved expansion state
		const key = `msg_expanded_${message.id}`;
		const result = safeSessionStorage.get(key);
		if (result.success && result.data === '1') {
			expanded = true;
		} else if (!result.success) {
			console.warn('Failed to load message expansion state:', result.error);
		}
	});

	// Auto-expand generated code after idle if user hasn't interacted
	$effect(() => {
		if (message.generatedCode && !message.streaming && !message.error && !expanded) {
			const id = setTimeout(() => {
				expanded = true;
				const key = `msg_expanded_${message.id}`;
				safeSessionStorage.set(key, '1');
			}, 2000);
			return () => clearTimeout(id);
		}
	});

	function toggleExpanded() {
		expanded = !expanded;
		const key = `msg_expanded_${message.id}`;
		const result = safeSessionStorage.set(key, expanded ? '1' : '0');
		if (!result.success) {
			console.warn('Failed to save message expansion state:', result.error);
		}
	}
</script>

<article
	class="{message.role === 'user' ? 'mb-3' : 'mb-8'} flex {message.role === 'user'
		? 'justify-end'
		: 'justify-start'} w-full {message.role === 'user' ? 'order-2' : 'order-1'}"
	aria-label={message.role === 'user' ? t('chat.userMessage') : t('chat.assistantMessage')}
	role="group"
>
	{#if message.role === 'user'}
		<!-- User message: Keep the card/bubble style -->
		<div class="flex justify-end">
			<div
				class="max-w-[80%] p-3 rounded-lg bg-slate-600 dark:bg-slate-700 text-slate-100 shadow-sm"
			>
				<div class="whitespace-pre-wrap text-sm">{message.content}</div>
			</div>
		</div>
	{:else}
		<!-- AI message: More integrated, minimal styling -->
		<div class="w-full">
			{#if message.error}
				<section
					class="p-4 rounded-lg bg-destructive/10 border border-destructive/20"
					role="alert"
					aria-live="polite"
				>
					<h4 class="text-destructive text-sm font-medium mb-2">Error</h4>
					<p class="text-destructive text-sm">{message.error}</p>
					<div class="mt-2">
						<button
							class="text-xs underline text-destructive hover:opacity-80"
							onclick={() => dispatch('retry', { messageId: message.id })}
							aria-label="Retry with default model"
						>
							Retry with default model
						</button>
					</div>
				</section>
			{:else if message.generatedCode && !message.streaming}
				<!-- Code generation result -->
				<section class="space-y-3" aria-labelledby={`code-header-${message.id}`}>
					<header
						class="flex items-center justify-between gap-2 text-sm text-muted-foreground"
						id={`code-header-${message.id}`}
					>
						<div class="flex items-center gap-2 min-w-0 flex-1">
							<div
								class="w-6 h-6 rounded-full bg-muted flex items-center justify-center flex-shrink-0"
								aria-label="AI Assistant"
							>
								<span class="text-xs font-medium" aria-hidden="true">AI</span>
							</div>
						</div>
						<div class="flex items-center gap-2 flex-shrink-0 text-xs">
							<time datetime={new Date(message.timestamp).toISOString()}
								>{formatTime(message.timestamp)}</time
							>
							{#if message.provider}
								<span
									class="px-1.5 py-0.5 rounded bg-muted/60"
									role="img"
									aria-label={`Generated by ${formatProvider(message.provider)}`}
								>
									{formatProvider(message.provider)}
								</span>
							{/if}
						</div>
					</header>

					{#if expanded}
						<pre
							id={`code-${message.id}`}
							class="font-mono text-xs whitespace-pre-wrap break-words max-h-96 overflow-auto rounded-lg bg-muted/30 border p-4"
							aria-label="Generated Svelte component code"
							role="code">{message.generatedCode}</pre>
					{:else}
						<div
							class="p-4 rounded-lg bg-muted/20 border border-dashed"
							role="region"
							aria-label="Code preview"
						>
							<p class="text-sm text-muted-foreground">
								{getCodePreview(message.generatedCode)} - Click "{t('actions.show')}" below to
								expand.
							</p>
						</div>
					{/if}
				</section>
			{:else}
				<!-- Regular AI text response -->
				<section class="space-y-2" aria-labelledby={`text-header-${message.id}`}>
					<header
						class="flex items-center justify-between gap-2 text-sm text-muted-foreground mb-2"
						id={`text-header-${message.id}`}
					>
						<div class="flex items-center gap-2">
							<div
								class="w-6 h-6 rounded-full bg-muted flex items-center justify-center flex-shrink-0"
								aria-label="AI Assistant"
							>
								<span class="text-xs font-medium" aria-hidden="true">AI</span>
							</div>
						</div>
						<div class="flex items-center gap-2 flex-shrink-0 text-xs">
							<time datetime={new Date(message.timestamp).toISOString()}
								>{formatTime(message.timestamp)}</time
							>
							{#if message.provider}
								<span
									class="px-1.5 py-0.5 rounded bg-muted/60"
									role="img"
									aria-label={`Generated by ${formatProvider(message.provider)}`}
								>
									{formatProvider(message.provider)}
								</span>
							{/if}
						</div>
					</header>
					<div
						class="whitespace-pre-wrap text-sm leading-relaxed"
						role="region"
						aria-label="AI response"
					>
						{message.content}
					</div>
					{#if message.streaming}
						<div
							class="flex items-center gap-1 mt-3 text-xs text-muted-foreground"
							role="status"
							aria-live="polite"
							aria-label={t('chat.generating')}
						>
							<div class="w-1 h-1 bg-current rounded-full animate-pulse" aria-hidden="true"></div>
							<div
								class="w-1 h-1 bg-current rounded-full animate-pulse delay-100"
								aria-hidden="true"
							></div>
							<div
								class="w-1 h-1 bg-current rounded-full animate-pulse delay-200"
								aria-hidden="true"
							></div>
							<span class="ml-2">{t('chat.generating')}</span>
						</div>
					{/if}
				</section>
			{/if}
		</div>
	{/if}

	<!-- Simplified action buttons for assistant code -->
	{#if message.role === 'assistant' && message.generatedCode && !message.streaming && !message.error}
		<div
			class="mt-1 flex items-center justify-between text-xs text-muted-foreground"
			aria-label={t('chat.messageActions')}
		>
			<button
				class="flex items-center gap-2 hover:text-foreground transition-colors cursor-pointer px-2 py-1 rounded hover:bg-accent/50"
				onclick={toggleExpanded}
				aria-expanded={expanded}
				aria-controls={`code-${message.id}`}
				title={expanded ? t('actions.hide') : t('actions.show')}
				aria-label={expanded ? t('actions.hide') : t('actions.show')}
			>
				{#if expanded}
					<EyeOffIcon class="w-4 h-4" />
				{:else}
					<EyeIcon class="w-4 h-4" />
				{/if}
				<span>{expanded ? t('actions.hide') : t('actions.show')}</span>
			</button>

			<div class="flex items-center gap-1">
				<button
					class="flex items-center gap-1 hover:text-foreground transition-colors cursor-pointer px-2 py-1 rounded hover:bg-accent/50"
					onclick={handleUseCode}
					aria-label={t('a11y.useCodeInEditor')}
					title={t('actions.useCode')}
				>
					<CodeIcon class="w-4 h-4" />
				</button>

				<button
					class="flex items-center gap-1 hover:text-foreground transition-colors cursor-pointer px-2 py-1 rounded hover:bg-accent/50"
					onclick={handleCopy}
					aria-label={t('a11y.copyCode')}
					title={t('actions.copy')}
				>
					<CopyIcon class="w-4 h-4" />
				</button>

				<button
					class="flex items-center gap-1 hover:text-foreground transition-colors cursor-pointer px-2 py-1 rounded hover:bg-accent/50"
					onclick={handleRefine}
					aria-label={t('a11y.refineComponent')}
					title={t('actions.refine')}
				>
					<Wand2Icon class="w-4 h-4" />
				</button>
			</div>
		</div>
	{/if}
</article>
